export const COMPUTER_LIST_REQUEST = 'COMPUTER_LIST_REQUEST';
export const COMPUTER_LIST_SUCCESS = 'COMPUTER_LIST_SUCCESS';
export const COMPUTER_LIST_FAIL = 'COMPUTER_LIST_FAIL';

export const COMPUTER_DELETE_REQUEST = 'COMPUTER_DELETE_REQUEST';
export const COMPUTER_DELETE_SUCCESS = 'COMPUTER_DELETE_SUCCESS';
export const COMPUTER_DELETE_FAIL = 'COMPUTER_DELETE_FAIL';
export const COMPUTER_DELETE_RESET = 'COMPUTER_DELETE_RESET';

export const COMPUTER_CREATE_REQUEST = 'COMPUTER_CREATE_REQUEST';
export const COMPUTER_CREATE_SUCCESS = 'COMPUTER_CREATE_SUCCESS';
export const COMPUTER_CREATE_FAIL = 'COMPUTER_CREATE_FAIL';
export const COMPUTER_CREATE_RESET = 'COMPUTER_CREATE_RESET';

export const COMPUTER_ADD_ITEM = 'COMPUTER_ADD_ITEM';
export const COMPUTER_REMOVE_ITEM = 'COMPUTER_REMOVE_ITEM';
export const COMPUTER_EMPY = 'COMPUTER_EMPY';
