
export const HARDWARE_POST_LIST_REQUEST = 'HARDWARE_POST_LIST_REQUEST';
export const HARDWARE_POST_LIST_SUCCESS = 'HARDWARE_POST_LIST_SUCCESS';
export const HARDWARE_POST_LIST_FAIL = 'HARDWARE_POST_LIST_FAIL';

export const HARDWARE_POST_DELETE_REQUEST = 'HARDWARE_POST_DELETE_REQUEST';
export const HARDWARE_POST_DELETE_SUCCESS = 'HARDWARE_POST_DELETE_SUCCESS';
export const HARDWARE_POST_DELETE_FAIL = 'HARDWARE_POST_DELETE_FAIL';
export const HARDWARE_POST_DELETE_RESET = 'HARDWARE_POST_DELETE_RESET';

export const HARDWARE_POST_CREATE_REQUEST = 'HARDWARE_POST_CREATE_REQUEST';
export const HARDWARE_POST_CREATE_SUCCESS = 'HARDWARE_POST_CREATE_SUCCESS';
export const HARDWARE_POST_CREATE_FAIL = 'HARDWARE_POST_CREATE_FAIL';
export const HARDWARE_POST_CREATE_RESET = 'HARDWARE_POST_CREATE_RESET';