export const NOTE_CREATE_REQUEST = 'NOTE_CREATE_REQUEST';
export const NOTE_CREATE_SUCCESS = 'NOTE_CREATE_SUCCESS';
export const NOTE_CREATE_FAIL = 'NOTE_CREATE_FAIL';
export const NOTE_CREATE_RESET = 'NOTE_CREATE_RESET';
export const NOTE_LIST_REQUEST = 'NOTE_LIST_REQUEST';
export const NOTE_LIST_SUCCESS = 'NOTE_LIST_SUCCESS';
export const NOTE_LIST_FAIL = 'NOTE_LIST_FAIL';
export const NOTE_LIST_RESET = 'NOTE_LIST_RESET';
export const NOTE_UPDATE_SUCCESS = 'NOTE_UPDATE_SUCCESS';
export const NOTE_UPDATE_REQUEST = 'NOTE_UPDATE_REQUEST';
export const NOTE_UPDATE_FAIL = 'NOTE_UPDATE_FAIL';
export const NOTE_UPDATE_RESET = 'NOTE_UPDATE_RESET';

export const NOTE_ARCHIVE_SUCCESS = 'NOTE_ARCHIVE_SUCCESS';
// export const NOTE_SIGNIN_SUCCESS = 'ADMIN_SIGNIN_SUCCESS';
// export const NOTE_SIGNIN_FAIL = 'ADMIN_SIGNIN_FAIL';
// export const NOTE_SIGNOUT = 'ADMIN_SIGNOUT';