export const NOTE_CREATE_REQUEST = 'NOTE_CREATE_REQUEST';
export const NOTE_CREATE_SUCCESS = 'NOTE_CREATE_SUCCESS';
export const NOTE_CREATE_FAIL = 'NOTE_CREATE_FAIL';
export const NOTE_CREATE_RESET = 'NOTE_CREATE_RESET';
// export const NOTE_SIGNIN_SUCCESS = 'ADMIN_SIGNIN_SUCCESS';
// export const NOTE_SIGNIN_FAIL = 'ADMIN_SIGNIN_FAIL';
// export const NOTE_SIGNOUT = 'ADMIN_SIGNOUT';