export const QUOTATION_SAVE_CLIENT = 'QUOTATION_SAVE_CLIENT';

export const QUOTATION_CREATE_REQUEST = 'QUOTATION_CREATE_REQUEST';
export const QUOTATION_CREATE_SUCCESS = 'QUOTATION_CREATE_SUCCESS';
export const QUOTATION_CREATE_FAIL = 'QUOTATION_CREATE_FAIL';
export const QUOTATION_CREATE_RESET = 'QUOTATION_CREATE_RESET';

export const QUOTATION_LIST_REQUEST = 'QUOTATION_LIST_REQUEST';
export const QUOTATION_LIST_SUCCESS = 'QUOTATION_LIST_SUCCESS';
export const QUOTATION_LIST_FAIL = 'QUOTATION_LIST_FAIL';
export const QUOTATION_LIST_RESET = 'QUOTATION_LIST_RESET';

export const QUOTATION_DELETE_REQUEST = 'QUOTATION_DELETE_REQUEST';
export const QUOTATION_DELETE_SUCCESS = 'QUOTATION_DELETE_SUCCESS';
export const QUOTATION_DELETE_FAIL = 'QUOTATION_DELETE_FAIL';
export const QUOTATION_DELETE_RESET = 'QUOTATION_DELETE_RESET';

export const QUOTATION_ADD_ITEM = 'QUOTATION_ADD_ITEM';
export const QUOTATION_REMOVE_ITEM = 'QUOTATION_REMOVE_ITEM';

export const QUOTATION_DETAILS_REQUEST = 'QUOTATION_DETAILS_REQUEST';
export const QUOTATION_DETAILS_SUCCESS = 'QUOTATION_DETAILS_SUCCESS';
export const QUOTATION_DETAILS_FAIL = 'QUOTATION_DETAILS_FAIL';
export const QUOTATION_DETAILS_RESET = 'QUOTATION_DETAILS_RESET';

export const QUOTATION_EMPY = 'QUOTATION_EMPY';
