export const SELL_SAVE_CLIENT = 'SELL_SAVE_CLIENT';

export const SELL_CREATE_REQUEST = 'SELL_CREATE_REQUEST';
export const SELL_CREATE_SUCCESS = 'SELL_CREATE_SUCCESS';
export const SELL_CREATE_FAIL = 'SELL_CREATE_FAIL';
export const SELL_CREATE_RESET = 'SELL_CREATE_RESET';

export const SELL_LIST_REQUEST = 'SELL_LIST_REQUEST';
export const SELL_LIST_SUCCESS = 'SELL_LIST_SUCCESS';
export const SELL_LIST_FAIL = 'SELL_LIST_FAIL';
export const SELL_LIST_RESET = 'SELL_LIST_RESET';

export const SELL_DELETE_REQUEST = 'SELL_DELETE_REQUEST';
export const SELL_DELETE_SUCCESS = 'SELL_DELETE_SUCCESS';
export const SELL_DELETE_FAIL = 'SELL_DELETE_FAIL';
export const SELL_DELETE_RESET = 'SELL_DELETE_RESET';

export const SELL_ADD_ITEM = 'SELL_ADD_ITEM';
export const SELL_REMOVE_ITEM = 'SELL_REMOVE_ITEM';

export const SELL_DETAILS_REQUEST = 'SELL_DETAILS_REQUEST';
export const SELL_DETAILS_SUCCESS = 'SELL_DETAILS_SUCCESS';
export const SELL_DETAILS_FAIL = 'SELL_DETAILS_FAIL';
export const SELL_DETAILS_RESET = 'SELL_DETAILS_RESET';

export const SELL_EMPY = 'SELL_EMPY';
